version: '3.4'
services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - firstApiCS:/data/db
    networks:
      - app

networks:
  app:

volumes:
  firstApiCS: